Repository ktb-23/healthkungya-frontend, pull requests merged in 2024-08, with the labels that each got.

#11 Feat7/exercise log
  .eslintrc.js
  package.json
  src/App.jsx
  src/api/useDeleteExlog.jsx
  src/api/useGetExlog.jsx
  src/api/useInsertExlog.jsx
  src/api/useLogin.jsx
  src/api/useSearch.jsx
  src/api/useUpdateExlog.jsx
  src/components/ExList.jsx
  src/components/Search.jsx
  src/components/styles/Button.module.scss
  src/components/styles/ExList.module.scss
  src/components/styles/Input.module.scss
  src/components/styles/Search.module.scss
  src/containers/ExForm.jsx
  src/containers/LoginForm.jsx
  src/containers/styles/ExForm.module.scss
  src/hooks/useExerciseLog.jsx
  src/index.css
  src/index.scss
  src/main.jsx
  src/picture/arrow.png
  src/picture/search.svg
  src/provider/ex상태관리폴더.txt
  src/provider/reducers/rootReducer.js
  src/provider/slices/ex.js
  src/provider/slices/exitem.js
  src/provider/store.js
  src/routes/PageRoutes.jsx
  yarn.lock
Labels: 기능 추가, D-2

#14 Feat5/foodform
  package-lock.json
  src/components/UseDailyData.jsx
  src/containers/ExForm.jsx
  src/containers/FoodForm.jsx
  src/containers/MainForm.jsx
  src/containers/reducers/FoodReducer.jsx
  src/containers/styles/FoodForm.scss
  yarn.lock
Labels: P-2

#19 Feat9/ex graph
  src/api/useFetchWeeklyExerciseGraph.jsx
  src/api/useFetchWeeklyWeightGraph.jsx
  src/api/useGetWeight.jsx
  src/api/useInsertWeight.jsx
  src/api/useUpdateWeight.jsx
  src/components/ExList.jsx
  src/components/styles/Input.module.scss
  src/containers/ExForm.jsx
  src/containers/GraphForm.jsx
  src/containers/MainForm.jsx
  src/hooks/useExerciseLog.jsx
  src/hooks/useWeight.jsx
  src/provider/slices/exitem.js
Labels: 기능 추가, 리펙토링, D-0, P-1

#21 Feat10/data
  src/App.jsx
  src/components/Calendar.jsx
  src/components/UseDailyData.jsx
  src/components/styles/Calendar.scss
  src/containers/FoodForm.jsx
  src/containers/MainForm.jsx
  src/containers/reducers/FoodReducer.jsx
  src/routes/PageRoutes.jsx
  src/routes/StartRoutes.jsx
  yarn.lock
Labels: P-2

#22 Feat11/main connect
  src/api/useCheckDuplicate.jsx
  src/api/useDeleteExlog.jsx
  src/api/useDeleteProfile.jsx
  src/api/useFetchWeeklyExerciseGraph.jsx
  src/api/useFetchWeeklyWeightGraph.jsx
  src/api/useGetExlog.jsx
  src/api/useGetProfile.jsx
  src/api/useGetWeight.jsx
  src/api/useInsertExlog.jsx
  src/api/useInsertWeight.jsx
  src/api/useLogin.jsx
  src/api/useSearch.jsx
  src/api/useSignup.jsx
  src/api/useUpdateExlog.jsx
  src/api/useUpdateProfile.jsx
  src/api/useUpdateWeight.jsx
  src/components/ExList.jsx
  src/components/Navbar.jsx
  src/components/Profile.jsx
  src/components/ProfileSetting.jsx
  src/components/Setting.jsx
  src/components/styles/Navbar.scss
  src/components/styles/Output.module.scss
  src/config/apiConfig.jsx
  src/containers/ExForm.jsx
  src/containers/LoginForm.jsx
  src/containers/MainForm.jsx
  src/containers/SignupForm.jsx
  src/containers/StartForm.jsx
  src/containers/styles/MainForm.scss
  src/hooks/useExerciseLog.jsx
  src/hooks/useWeight.jsx
  src/reducers/Profile.jsx
Labels: 기능 추가, 긴급, OVERDUE, D-0

#24 feat: 메인폼 달력에 운동기록 추가:
  src/api/useGetAllDateExlog.jsx
  src/components/Calendar.jsx
  src/components/ExList.jsx
  src/components/styles/ExList.module.scss
  src/containers/ExForm.jsx
  src/hooks/useWeight.jsx
Labels: 기능 추가, D-0, P-1

#27 Feat14/refactor style
  src/components/Calendar.jsx
  src/components/Navbar.jsx
  src/components/Profile.jsx
  src/components/styles/Button.module.scss
  src/components/styles/Calendar.scss
  src/components/styles/ExList.module.scss
  src/components/styles/Index.module.scss
  src/components/styles/Input.module.scss
  src/components/styles/Navbar.scss
  src/components/styles/Output.module.scss
  src/components/styles/Photo.scss
  src/components/styles/Profile.scss
  src/components/styles/Search.module.scss
  src/containers/FixForm.jsx
  src/containers/FoodForm.jsx
  src/containers/GraphForm.jsx
  src/containers/MainForm.jsx
  src/containers/styles/ExForm.module.scss
  src/containers/styles/FixForm.scss
  src/containers/styles/FoodForm.scss
  src/containers/styles/GraphForm.scss
  src/containers/styles/MainForm.scss
  src/containers/styles/ProfileSettingForm.module.scss
  src/containers/styles/SettingForm.module.scss
Labels: 디자인 수정, D-3

#30 feat: 유저 이미지 업데이트 :
  src/api/useUploadProfileImage.jsx
  src/components/ProfileSetting.jsx
  src/components/styles/Profile.scss
Labels: 기능 추가, D-3, P-3

#29 development 환경 CI/CD를 위한 github action 설정 파일 추가
  .github/workflows/development-ci-cd.yaml
Labels: 기능 추가
