Repository ktb-23/healthkungya-frontend, pull requests merged in 2024-07, with the labels that each got.

#3 Feat1/register
  .prettierrc.json
  .setting.json
  package.json
  src/App.css
  src/App.jsx
  src/api/useCheckDuplicate.jsx
  src/api/useSignup.jsx
  src/components/Button.jsx
  src/components/Input.jsx
  src/components/styles/Button.module.scss
  src/components/styles/Input.module.scss
  src/config/validation.jsx
  src/containers/LoginForm.jsx
  src/containers/SignupForm.jsx
  src/containers/StartForm.jsx
  src/containers/styles/LoginForm.module.scss
  src/containers/styles/SignupForm.module.scss
  src/containers/styles/StartForm.module.scss
  src/hooks/useCheckDuplicate.jsx
  src/hooks/useDebounce.jsx
  src/hooks/useFormHandler.jsx
  src/hooks/useLocalStorage.jsx
  src/hooks/useValidation.jsx
  src/index.scss
  src/main.jsx
  src/picture/backicon.svg
  src/picture/logo.png
  src/reducers/Register.jsx
  src/routes/StartRoutes.jsx
  yarn.lock
Labels: 기능 추가, 리펙토링, 버그 수정, D-2, P-2

#5 Feat3/login
  package.json
  src/api/exapi.txt
  src/api/useCheckDuplicate.jsx
  src/api/useLogin.jsx
  src/api/useSignup.jsx
  src/components/styles/Input.module.scss
  src/containers/LoginForm.jsx
  src/containers/StartForm.jsx
  src/containers/styles/LoginForm.module.scss
  src/hooks/useValidation.jsx
  src/reducers/Login.jsx
  yarn.lock
Labels: 기능 추가, D-2, P-2

#6 Feat2/fixform
  README.md
  src/components/Calendar.jsx
  src/components/EditButton.jsx
  src/components/Graph.jsx
  src/components/Index.jsx
  src/components/Navbar.jsx
  src/components/Output.jsx
  src/components/Photo.jsx
  src/components/Profile.jsx
  src/components/Search.jsx
  src/components/Select.jsx
  src/components/Toggle.jsx
  src/components/styles/Calendar.scss
  src/components/styles/Index.module.scss
  src/components/styles/Input.module.scss
  src/components/styles/Navbar.scss
  src/components/styles/Profile.scss
  src/containers/EditForm.jsx
  src/containers/ExForm.jsx
  src/containers/FixForm.jsx
  src/containers/FoodForm.jsx
  src/containers/GraphForm.jsx
  src/containers/MainForm.jsx
  src/containers/SettingForm.jsx
  src/containers/styles/MainForm.scss
  src/index.css
  src/index.js
  src/picture/exindex.svg
  src/picture/foodindex.svg
  src/picture/logo.png
  src/picture/sample.jpg
  src/picture/sample.png
  src/picture/sample.svg
  src/picture/weightindex.svg
  src/routes/StartRoutes.jsx
  yarn.lock
Labels: P-2
