Repository ktb-23/healthkungya-frontend, pull requests merged in 2024-09, with the labels that each got.

#33 Feat13/fooddata
  package.json
  src/api/useFoodUpload.jsx
  src/components/UseDailyData.jsx
  src/containers/FoodForm.jsx
  src/containers/MainForm.jsx
  src/containers/reducers/FoodReducer.jsx
  src/containers/styles/FoodForm.scss
  vite.config.js
  yarn.lock
Labels: P-1

#35 feat: 리드미.md 수정 #34
  README.md
Labels: P-3

#39 Fix16/bug fix
  package-lock.json
  src/components/Calendar.jsx
  src/containers/GraphForm.jsx
  src/containers/MainForm.jsx
  src/hooks/useExerciseLog.jsx
Labels: 버그 수정, OVERDUE, D-0

#50 Feat18/color
  src/components/styles/Calendar.scss
  src/containers/FoodForm.jsx
  src/containers/MainForm.jsx
  src/containers/styles/FoodForm.scss
  src/picture/alert.svg
Labels: D-1

#53 feat: 버그 수정
  src/containers/FoodForm.jsx
Labels: 버그 수정, OVERDUE, D-0
